title: Jieda Li # your name (or website title) here
logo: "/images/jieda_cropped.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Storyteller 
  <br><br>
  Former Hardware System Engineer with Apple
  <br><br>
  <a href="https://github.com/jiedali">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
