title: Jieda Li # your name (or website title) here
logo: "/images/jieda_cropped.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master's degree in data science from Northwestern University (MSiA theta cohort)
  A Data Storyteller, A Mom, A naturalist and minimalist
  <br><br>
  Former Hardware Engineer with Apple and Oracle
  <br><br>
  <a href="https://github.com/jiedali">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
